title:              Herb Silverman
email:              silvermanh@gmail.com
description:        Life Lessons Learned
author:             Herb Silverman
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   
github_username:    herbsilverman
facebook_username:  herb.silverman.5
instagram_username:  
linkedin_username:  herbsilverman

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Category
collections:
  category:
    output: true

